# Generated by Django 3.0.4 on 2020-03-17 15:43

from django.db import migrations


def create_queue(apps, schema_editor):
    TaskQueue = apps.get_model('task_queue', 'TaskQueue')
    TaskQueue.objects.create(
        name='Default Queue',
        celery_queue='celery'
    )


def undo_create_queue(apps, schema_editor):
    TaskQueue = apps.get_model('task_queue', 'TaskQueue')
    TaskQueue.objects.filter(
        celery_queue='celery'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_queue, undo_create_queue)
    ]
