# Generated by Django 3.0.4 on 2020-03-24 11:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0002_create_default_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished At'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activity At'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='last_state',
            field=jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='JSON Last State'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='last_traceback',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Last Traceback'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='log',
            field=models.TextField(blank=True, default='', verbose_name='Log'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='started_running_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started Running At'),
        ),
    ]
