# Generated by Django 3.0.4 on 2020-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0003_auto_20200324_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetaskgroup',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tasks Priority'),
        ),
    ]
