# Generated by Django 3.0.4 on 2020-03-24 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('task_queue', '0004_queuetaskgroup_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledQueueTaskGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='Priority')),
                ('operation_type', models.CharField(choices=[('_op_append', 'Append to queue end'), ('_op_insert', 'Insert by priority'), ('_op_run', 'Run now'), ('_op_state', 'Run on next state save'), ('_op_next', 'Run after current task')], max_length=25, verbose_name='Operation Type')),
                ('crontab_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.CrontabSchedule', verbose_name='Crontab Schedule')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask', verbose_name='Periodic Task')),
                ('queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_queue.TaskQueue', verbose_name='Queue')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_queue.QueueTaskGroup', verbose_name='Queue Task Group')),
            ],
            options={
                'verbose_name': 'Scheduled Queue Task Group',
                'verbose_name_plural': 'Scheduled Queue Task Groups',
                'ordering': ('task_group',),
            },
        ),
    ]
