# Generated by Django 3.0.4 on 2020-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0005_scheduledqueuetaskgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledqueuetaskgroup',
            name='disabled',
            field=models.BooleanField(default=False, help_text='If disabled, the task wont be executed', verbose_name='Disabled'),
        ),
    ]
