# Generated by Django 3.0.4 on 2020-03-25 14:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0006_scheduledqueuetaskgroup_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='task_args',
            field=jsonfield.fields.JSONField(blank=True, default=list, verbose_name='Task args'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='task_kwargs',
            field=jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='Task kwargs'),
        ),
        migrations.AlterField(
            model_name='queuetasktemplate',
            name='task_args',
            field=jsonfield.fields.JSONField(blank=True, default=list, verbose_name='Task args'),
        ),
        migrations.AlterField(
            model_name='queuetasktemplate',
            name='task_kwargs',
            field=jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='Task kwargs'),
        ),
    ]
