# Generated by Django 3.0.4 on 2020-04-01 10:49

from django.db import migrations
import jsonfield.fields
import task_queue.json


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0007_auto_20200325_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='last_state',
            field=jsonfield.fields.JSONField(blank=True, default=dict, load_kwargs={'cls': task_queue.json.DateJSONDecoder}, verbose_name='JSON Last State'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='task_args',
            field=jsonfield.fields.JSONField(blank=True, default=list, load_kwargs={'cls': task_queue.json.DateJSONDecoder}, verbose_name='Task args'),
        ),
        migrations.AlterField(
            model_name='queuetask',
            name='task_kwargs',
            field=jsonfield.fields.JSONField(blank=True, default=dict, load_kwargs={'cls': task_queue.json.DateJSONDecoder}, verbose_name='Task kwargs'),
        ),
        migrations.AlterField(
            model_name='queuetasktemplate',
            name='task_args',
            field=jsonfield.fields.JSONField(blank=True, default=list, load_kwargs={'cls': task_queue.json.DateJSONDecoder}, verbose_name='Task args'),
        ),
        migrations.AlterField(
            model_name='queuetasktemplate',
            name='task_kwargs',
            field=jsonfield.fields.JSONField(blank=True, default=dict, load_kwargs={'cls': task_queue.json.DateJSONDecoder}, verbose_name='Task kwargs'),
        ),
    ]
