# Generated by Django 3.0.4 on 2020-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0008_auto_20200401_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='task_name',
            field=models.CharField(default='Queued Task', max_length=255, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='queuetasktemplate',
            name='task_name',
            field=models.CharField(default='Queued Task', max_length=255, verbose_name='Task Name'),
        ),
    ]
