# Generated by Django 3.0.4 on 2020-04-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0009_auto_20200407_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuetask',
            name='last_state',
        ),
    ]
