# Generated by Django 3.0.4 on 2020-04-13 16:20

from django.db import migrations, models
import task_queue.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0010_remove_queuetask_last_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetask',
            name='last_state',
            field=models.FileField(blank=True, null=True, upload_to=task_queue.models.queue_task_last_state_upload_to, verbose_name='Last State'),
        ),
    ]
