# Generated by Django 3.0.4 on 2020-04-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0011_queuetask_last_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuetask',
            name='log',
        ),
    ]
