# Generated by Django 3.0.4 on 2020-04-13 16:49

from django.db import migrations, models
import task_queue.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0012_remove_queuetask_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetask',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to=task_queue.models.queue_task_log_upload_to, verbose_name='Log'),
        ),
    ]
