# Generated by Django 3.0.4 on 2020-04-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0013_queuetask_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTaskGroupAtGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('children_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_children_group', to='task_queue.QueueTaskGroup', verbose_name='Queue Task Group')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='task_queue.QueueTaskGroup', verbose_name='Queue Task Group')),
            ],
            options={
                'verbose_name': 'Queue Task At Group',
                'verbose_name_plural': 'Queue Tasks At Group',
                'ordering': ('order', 'children_group'),
            },
        ),
        migrations.AddField(
            model_name='queuetaskgroup',
            name='group_groups',
            field=models.ManyToManyField(blank=True, through='task_queue.QueueTaskGroupAtGroup', to='task_queue.QueueTaskGroup', verbose_name='Task Groups'),
        ),
    ]
