import json
import typing

from task_queue.constants import (
    OPERATION_TYPE_APPEND, OPERATION_TYPE_INSERT, OPERATION_TYPE_RUN_NOW, OPERATION_TYPE_RUN_STATE)

OPERATION_TYPE = typing.Literal[
    OPERATION_TYPE_RUN_STATE, OPERATION_TYPE_RUN_NOW, OPERATION_TYPE_INSERT, OPERATION_TYPE_APPEND]
